### ISSUE TITLE
[Feature Request] re-add `gh://` etc.

### ISSUE THREAD

**Issue by retronbv** [1hostjs/1host-next#11]
**Is your feature request related to a problem? Please describe.**
a wgyt removed a feature I made

**Describe the solution you'd like**
Bringing it back

**Describe alternatives you've considered**
adding it back

**Additional context**
wgyt asked me to make this

**Comment by retronbv** [comment]
Should be prio: 1

**Comment by wgyt** [comment]
> Should be prio: 1
> Edit: this is a highly requested feature (from me)

prio 1 is reserved for critical must do stuff

**Comment by retronbv** [comment]
> > Should be prio: 1
> > Edit: this is a highly requested feature (from me)
> 
> prio 1 is reserved for critical must do stuff

this is really critical and must do

**Comment by GrahamSH-LLK** [comment]
No. NPM has built-in support for git repositories, so we can do it that way. Just use `require('packagename')`
Also, I removed it
